### ISSUE TITLE
VUE_APP_SLACK_WEBHOOK_URL を更新する

### ISSUE THREAD

**Issue by guppy0356** [rights-s/flocks-app-release#4]
VUE_APP_SLACK_WEBHOOK_URL が間違っており、フィードバックの投稿に失敗している。
原因は Webhook URL に誤りがあり次の issue のコメントにある URL が正しい。

https://github.com/rights-s/flocks-app/issues/204#issuecomment-1196277123

**Comment by rights-uchida** [comment]
更新しました
